// Generated by CoffeeScript 1.9.3
(function() {
  window.Act = function(init_state, timeout) {
    var obj;
    if (!(Imuta.is_number(timeout)) || (timeout <= 0)) {
      throw new Error("Act timeout is number >= 0");
    }
    obj = {
      state: Imuta.clone(init_state),
      queue: [],
      init: function() {
        var error, this_ref;
        try {
          while (this.queue.length !== 0) {
            this.state = Imuta.clone(this.queue.shift()(this.state));
          }
        } catch (_error) {
          error = _error;
          console.log("Actor error");
          console.log(error);
        }
        this_ref = this;
        return setTimeout((function() {
          return this_ref.init();
        }), timeout);
      },
      cast: function(func) {
        if ((func.length === 1) && Imuta.is_function(func)) {
          this.queue.push(Imuta.clone(func));
          return this.queue.length;
        } else {
          throw new Error("Act expects functions arity == 1 (single arg is actor's state)");
        }
      },
      get: function() {
        return Imuta.clone(this.state);
      }
    };
    obj.init();
    return obj;
  };

}).call(this);
